from dataclasses import dataclass
from decimal import Decimal
from typing import Optional, Dict, Any, List
from domain.value_objects import Symbol, ExchangeTimestamp


@dataclass(frozen=True)
class FeatureEventRecord:
    """Represents a historical feature state paired with realized forward returns for research validation."""
    timestamp: ExchangeTimestamp
    symbol: Symbol
    market_regime: str

    # Microstructure Features
    obi: Decimal
    obi_velocity: Decimal
    cvd: Decimal
    is_sweep: bool
    is_absorption: bool
    spread: Decimal
    depth_total: Decimal

    # Realized Forward Returns (relative percentage change, e.g. 0.0015 for +0.15%)
    forward_return_1m: Decimal
    forward_return_5m: Decimal
    forward_return_15m: Decimal
    forward_return_1h: Decimal

    def to_dict(self) -> Dict[str, Any]:
        """Deterministic dictionary serialization."""
        return {
            "timestamp": self.timestamp.to_millis(),
            "symbol": self.symbol.value,
            "market_regime": self.market_regime,
            "obi": str(self.obi),
            "obi_velocity": str(self.obi_velocity),
            "cvd": str(self.cvd),
            "is_sweep": self.is_sweep,
            "is_absorption": self.is_absorption,
            "spread": str(self.spread),
            "depth_total": str(self.depth_total),
            "forward_return_1m": str(self.forward_return_1m),
            "forward_return_5m": str(self.forward_return_5m),
            "forward_return_15m": str(self.forward_return_15m),
            "forward_return_1h": str(self.forward_return_1h)
        }


@dataclass(frozen=True)
class RegimeStats:
    """Statistical measurements computed over a specific market regime partition."""
    regime: str
    sample_count: int
    hit_rate: Decimal
    avg_return: Decimal
    median_return: Decimal
    volatility: Decimal
    max_drawdown: Decimal
    information_coefficient: Decimal
    feature_correlations: Dict[str, Decimal]  # feature_name -> correlation to 5m forward return
    feature_stats: Optional[Dict[str, Dict[str, Decimal]]] = None

    def to_dict(self) -> Dict[str, Any]:
        d = {
            "regime": self.regime,
            "sample_count": self.sample_count,
            "hit_rate": str(self.hit_rate),
            "avg_return": str(self.avg_return),
            "median_return": str(self.median_return),
            "volatility": str(self.volatility),
            "max_drawdown": str(self.max_drawdown),
            "information_coefficient": str(self.information_coefficient),
            "feature_correlations": {k: str(v) for k, v in self.feature_correlations.items()}
        }
        if self.feature_stats is not None:
            d["feature_stats"] = {
                feat: {m: str(val) for m, val in m_dict.items()}
                for feat, m_dict in self.feature_stats.items()
            }
        return d


@dataclass(frozen=True)
class CandidateSetup:
    """Immutable domain model representing a tactical setup candidate generated by the setup layer."""
    symbol: Symbol
    timestamp: ExchangeTimestamp
    setup_type: str  # "NGLS_SWEEP", "NGMR_REVERSION"
    direction: str  # "BUY", "SELL"
    trigger_price: Decimal
    stop_loss_level: Decimal
    take_profit_level: Decimal


